name: CI-docker
on:
  push: 
    branches: [master]
jobs: 
  docker: 
    runs-on: ubuntu-latest
    steps:
    -
      uses: actions/checkout@v2
    -
      run: |
        set -x
        cd data_analysis/Anagramas
        mv words.txt data
        docker build -t test --no-cache .
        docker run -v $PWD/data:/app/data:ro test
        docker logs $( docker ps -aq ) | grep '{1:'
        
